FROM mcr.microsoft.com/devcontainers/base:1.0-bookworm
RUN apt-get update -y
RUN apt-get -y install --no-install-recommends \
    libssl-dev \
    libreadline-dev \
    zlib1g-dev \
    autoconf \
    bison \
    build-essential \
    libyaml-dev \
    libncurses5-dev \
    libffi-dev \
    libgdbm-dev \
    libxml2-dev
